import { useLanguage } from "../LanguageContext";
import { motion } from "framer-motion";
import Layout from "../components/Layout";
import { CloudRain, Wind, ThermometerSun, Sprout, AlertTriangle } from "lucide-react";

export default function SmartWeather() {
  const { lang } = useLanguage();
  const t = lang === "ta";

  return (
    <Layout title={t ? "ஸ்மார்ட் வானிலை அறிவுரை" : "Smart Weather Advice"}>
      <div style={{ padding: "16px 16px 0" }}>

        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          style={{
            background: "linear-gradient(135deg, #2F80ED, #27AE60)",
            borderRadius: 20, padding: "18px",
            marginBottom: 20, color: "#fff",
            boxShadow: "0 8px 24px rgba(47,128,237,0.3)"
          }}
        >
          <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 8 }}>
            <div style={{ fontSize: 32 }}>🤖</div>
            <div>
              <p style={{ fontSize: 13, fontWeight: 700, opacity: 0.9, textTransform: "uppercase", letterSpacing: 0.5 }}>
                {t ? "AI பகுப்பாய்வு" : "AI Analysis"}
              </p>
              <h2 style={{ fontSize: 20, fontWeight: 800, margin: 0 }}>
                {t ? "இன்றைய பண்ணை முடிவு" : "Today's Farm Action"}
              </h2>
            </div>
          </div>
          <p style={{ fontSize: 14, opacity: 0.9, lineHeight: 1.5 }}>
            {t 
              ? "தற்போதைய வானிலை தரவுகளின் அடிப்படையில் AI கண்டறிந்த முடிவுகள்."
              : "Decisions generated by AI based on current local weather conditions."}
          </p>
        </motion.div>

        <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
          
          <motion.div
            initial={{ opacity: 0, x: -16 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.1 }}
            style={{ background: "#EDFBF1", borderRadius: 18, padding: "16px", border: "1px solid #A7F3D0" }}
          >
            <div style={{ display: "flex", alignItems: "flex-start", gap: 12 }}>
              <div style={{ width: 42, height: 42, borderRadius: 12, background: "#D1FAE5", color: "#065F46", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
                <CloudRain size={24} />
              </div>
              <div>
                <h3 style={{ fontSize: 15, fontWeight: 700, color: "#065F46", marginBottom: 4 }}>
                  {t ? "பாசனம் தேவையில்லை" : "No Irrigation Needed"}
                </h3>
                <p style={{ fontSize: 13, color: "#047857", lineHeight: 1.5 }}>
                  {t 
                   ? "இன்று மழை வாய்ப்பு இருப்பதால் பாசனம் செய்ய வேண்டாம். நீரை சேமிக்கவும்."
                   : "Rain probability is high today. Avoid irrigation to save water and prevent waterlogging."}
                </p>
              </div>
            </div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, x: -16 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.15 }}
            style={{ background: "#FEF9C3", borderRadius: 18, padding: "16px", border: "1px solid #FDE047" }}
          >
            <div style={{ display: "flex", alignItems: "flex-start", gap: 12 }}>
              <div style={{ width: 42, height: 42, borderRadius: 12, background: "#FEF08A", color: "#92400E", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
                <Wind size={24} />
              </div>
              <div>
                <h3 style={{ fontSize: 15, fontWeight: 700, color: "#92400E", marginBottom: 4 }}>
                  {t ? "தெளிப்பு தவிர்க்கவும்" : "Avoid Spraying"}
                </h3>
                <p style={{ fontSize: 13, color: "#854D0E", lineHeight: 1.5 }}>
                  {t 
                   ? "காற்று வேகம் அதிகம். பூச்சி மருந்து தெளிப்பதை ஒத்திவைக்கவும்."
                   : "Wind speed is high today. Postpone pesticide or fertilizer spraying to avoid drift."}
                </p>
              </div>
            </div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, x: -16 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.2 }}
            style={{ background: "#EBF4FF", borderRadius: 18, padding: "16px", border: "1px solid #BFDBFE" }}
          >
            <div style={{ display: "flex", alignItems: "flex-start", gap: 12 }}>
              <div style={{ width: 42, height: 42, borderRadius: 12, background: "#DBEAFE", color: "#1E40AF", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
                <Sprout size={24} />
              </div>
              <div>
                <h3 style={{ fontSize: 15, fontWeight: 700, color: "#1E40AF", marginBottom: 4 }}>
                  {t ? "அறுவடை கவனமாக தேவை" : "Harvest Carefully"}
                </h3>
                <p style={{ fontSize: 13, color: "#1D4ED8", lineHeight: 1.5 }}>
                  {t 
                   ? "அடுத்த 2 நாட்கள் மழை இருக்கலாம். அறுத்த பயிரை பாதுகாப்பாக வைக்கவும்."
                   : "Rain expected in the next 2 days. Protect any harvested crops immediately."}
                </p>
              </div>
            </div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, x: -16 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.25 }}
            style={{ background: "#FFF5F5", borderRadius: 18, padding: "16px", border: "1px solid #FECACA" }}
          >
            <div style={{ display: "flex", alignItems: "flex-start", gap: 12 }}>
              <div style={{ width: 42, height: 42, borderRadius: 12, background: "#FEE2E2", color: "#DC2626", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
                <ThermometerSun size={24} />
              </div>
              <div>
                <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 4 }}>
                  <AlertTriangle size={16} color="#DC2626" />
                  <h3 style={{ fontSize: 15, fontWeight: 700, color: "#DC2626", margin: 0 }}>
                    {t ? "வெப்ப எச்சரிக்கை" : "Heat Warning"}
                  </h3>
                </div>
                <p style={{ fontSize: 13, color: "#B91C1C", lineHeight: 1.5 }}>
                  {t 
                   ? "பிற்பகலில் அதிக வெப்பம். உச்சி வெயிலில் வயல் வேலையை குறைக்கவும்."
                   : "High temperature in the afternoon. Avoid strenuous field work during peak sunlight hours."}
                </p>
              </div>
            </div>
          </motion.div>

        </div>
      </div>
    </Layout>
  );
}